# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherRx' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherRx
  pod 'Alamofire', '~> 5.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5.1.1'
  pod 'RxGesture'
  pod 'XCoordinator', '~> 2.0'
  pod 'XCoordinator/RxSwift', '~> 2.0'
  pod 'Kingfisher', '~> 5.0'
  pod 'Action'
  pod 'Material', '~> 3.1.0'
  pod 'SwiftGifOrigin', '~> 1.7.0'
end
